# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# Start AeroSpace at login
start-at-login = true

# Gaps
[gaps]
inner.horizontal = 10
inner.vertical   = 10
outer.left       = 20
outer.bottom     = 20
outer.top        = 30
outer.right      = 20

[mode.main.binding]
# Raccourcis de base (Alt + touches)
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'
alt-f = 'fullscreen'

# App shortcuts
alt-i = 'exec-and-forget open -a /Applications/Ghostty.app'


# Déplacer les fenêtres
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

cmd-1 = 'workspace 1'
cmd-2 = 'workspace 2'
alt-3 = 'workspace 3'

# Envoyer la fenêtre vers un workspace
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'


# Exclude Apps

# System reglages
[[on-window-detected]]
if.app-id = 'com.apple.systempreferences'
run = ['layout floating']

# Finder
[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = ['layout floating']